// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/orderbook/orderbook.proto

package orderbook

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderBook_GetSnapshot_FullMethodName = "/orderbook.OrderBook/GetSnapshot"
)

// OrderBookClient is the client API for OrderBook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderBookClient interface {
	GetSnapshot(ctx context.Context, in *OrderBookSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotReply, error)
}

type orderBookClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderBookClient(cc grpc.ClientConnInterface) OrderBookClient {
	return &orderBookClient{cc}
}

func (c *orderBookClient) GetSnapshot(ctx context.Context, in *OrderBookSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotReply)
	err := c.cc.Invoke(ctx, OrderBook_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderBookServer is the server API for OrderBook service.
// All implementations must embed UnimplementedOrderBookServer
// for forward compatibility.
type OrderBookServer interface {
	GetSnapshot(context.Context, *OrderBookSnapshotRequest) (*GetSnapshotReply, error)
	mustEmbedUnimplementedOrderBookServer()
}

// UnimplementedOrderBookServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderBookServer struct{}

func (UnimplementedOrderBookServer) GetSnapshot(context.Context, *OrderBookSnapshotRequest) (*GetSnapshotReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedOrderBookServer) mustEmbedUnimplementedOrderBookServer() {}
func (UnimplementedOrderBookServer) testEmbeddedByValue()                   {}

// UnsafeOrderBookServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderBookServer will
// result in compilation errors.
type UnsafeOrderBookServer interface {
	mustEmbedUnimplementedOrderBookServer()
}

func RegisterOrderBookServer(s grpc.ServiceRegistrar, srv OrderBookServer) {
	// If the following call panics, it indicates UnimplementedOrderBookServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderBook_ServiceDesc, srv)
}

func _OrderBook_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderBookSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderBookServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderBook_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderBookServer).GetSnapshot(ctx, req.(*OrderBookSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderBook_ServiceDesc is the grpc.ServiceDesc for OrderBook service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderBook_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderbook.OrderBook",
	HandlerType: (*OrderBookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnapshot",
			Handler:    _OrderBook_GetSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/orderbook/orderbook.proto",
}
