// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/orderbook/orderbook.proto

package orderbook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderBookSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookSnapshotRequest) Reset() {
	*x = OrderBookSnapshotRequest{}
	mi := &file_api_orderbook_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookSnapshotRequest) ProtoMessage() {}

func (x *OrderBookSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_orderbook_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookSnapshotRequest.ProtoReflect.Descriptor instead.
func (*OrderBookSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_orderbook_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *OrderBookSnapshotRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_orderbook_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_orderbook_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_orderbook_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type GetSnapshotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastUpdateId  string                 `protobuf:"bytes,2,opt,name=lastUpdateId,proto3" json:"lastUpdateId,omitempty"`
	Bids          []*Order               `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*Order               `protobuf:"bytes,4,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotReply) Reset() {
	*x = GetSnapshotReply{}
	mi := &file_api_orderbook_orderbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotReply) ProtoMessage() {}

func (x *GetSnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_orderbook_orderbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotReply.ProtoReflect.Descriptor instead.
func (*GetSnapshotReply) Descriptor() ([]byte, []int) {
	return file_api_orderbook_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *GetSnapshotReply) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetSnapshotReply) GetLastUpdateId() string {
	if x != nil {
		return x.LastUpdateId
	}
	return ""
}

func (x *GetSnapshotReply) GetBids() []*Order {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetSnapshotReply) GetAsks() []*Order {
	if x != nil {
		return x.Asks
	}
	return nil
}

var File_api_orderbook_orderbook_proto protoreflect.FileDescriptor

const file_api_orderbook_orderbook_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/orderbook/orderbook.proto\x12\torderbook\"2\n" +
	"\x18OrderBookSnapshotRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"5\n" +
	"\x05Order\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"\x9a\x01\n" +
	"\x10GetSnapshotReply\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\"\n" +
	"\flastUpdateId\x18\x02 \x01(\tR\flastUpdateId\x12$\n" +
	"\x04bids\x18\x03 \x03(\v2\x10.orderbook.OrderR\x04bids\x12$\n" +
	"\x04asks\x18\x04 \x03(\v2\x10.orderbook.OrderR\x04asks2^\n" +
	"\tOrderBook\x12Q\n" +
	"\vGetSnapshot\x12#.orderbook.OrderBookSnapshotRequest\x1a\x1b.orderbook.GetSnapshotReply\"\x00B@Z>github.com/ChethiyaNishanath/market-data-hub/cmd/api/orderbookb\x06proto3"

var (
	file_api_orderbook_orderbook_proto_rawDescOnce sync.Once
	file_api_orderbook_orderbook_proto_rawDescData []byte
)

func file_api_orderbook_orderbook_proto_rawDescGZIP() []byte {
	file_api_orderbook_orderbook_proto_rawDescOnce.Do(func() {
		file_api_orderbook_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_orderbook_orderbook_proto_rawDesc), len(file_api_orderbook_orderbook_proto_rawDesc)))
	})
	return file_api_orderbook_orderbook_proto_rawDescData
}

var file_api_orderbook_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_orderbook_orderbook_proto_goTypes = []any{
	(*OrderBookSnapshotRequest)(nil), // 0: orderbook.OrderBookSnapshotRequest
	(*Order)(nil),                    // 1: orderbook.Order
	(*GetSnapshotReply)(nil),         // 2: orderbook.GetSnapshotReply
}
var file_api_orderbook_orderbook_proto_depIdxs = []int32{
	1, // 0: orderbook.GetSnapshotReply.bids:type_name -> orderbook.Order
	1, // 1: orderbook.GetSnapshotReply.asks:type_name -> orderbook.Order
	0, // 2: orderbook.OrderBook.GetSnapshot:input_type -> orderbook.OrderBookSnapshotRequest
	2, // 3: orderbook.OrderBook.GetSnapshot:output_type -> orderbook.GetSnapshotReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_orderbook_orderbook_proto_init() }
func file_api_orderbook_orderbook_proto_init() {
	if File_api_orderbook_orderbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_orderbook_orderbook_proto_rawDesc), len(file_api_orderbook_orderbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_orderbook_orderbook_proto_goTypes,
		DependencyIndexes: file_api_orderbook_orderbook_proto_depIdxs,
		MessageInfos:      file_api_orderbook_orderbook_proto_msgTypes,
	}.Build()
	File_api_orderbook_orderbook_proto = out.File
	file_api_orderbook_orderbook_proto_goTypes = nil
	file_api_orderbook_orderbook_proto_depIdxs = nil
}
